- README.md
- package.json
- src/files.js
- src/reporter.js
rename `threshold` to `maxSize` with backward compatibility.
fix for #14
> Rename 'threshold' to 'maxSize', with backward compatibility

- README.md
Added mainly to act as a link to the npm package page. (which is good for showing usage of the package). Also shows the latest version number.
[visual diff](https://github.com/danyshaanan/bundlesize/commit/a1a91782bedbee44350b2583e6ef3e985ae9bb7b?short_path=04c6e90).
> Add npm banner

- __mocks__/axios.js
- __mocks__/github-build.js
- __tests__/__snapshots__/environment-test.js.snap
- __tests__/environment-test.js
- __tests__/integration/ci-test.js
- __tests__/integration/cli-test.js
- __tests__/parser-test.js
- __tests__/runner-test.js
- index.js
- package-lock.json
- package.json
- src/api.js
- src/build.js
- src/environment.js
- src/parser.js
- src/reporter.js
- src/runner.js
Some aspects of the tool are hard to test (like the push to the API or the CI env variables). It would be nice to have automated tests for this.
This PR adds a buttload of unit tests while it also decouples the code to make testing easier. This would now also enable a rally easy integration of https://github.com/siddharthkp/bundlesize/issues/9. A list of tests can be seen here:
https://travis-ci.org/siddharthkp/bundlesize/builds/249366081
Tests found in `__tests__/integration` test the whole process including the calls to the API and github. These packages are mocked away so no real requests are made.
This is as far as I came until now. Adding the missing test files should be straight forward. A merge would be nice regardless of that because I don't know when I will find the time to add …
> Add Unit- and Integration Tests

- src/api.js
Firebase does not like dots in the key names, we use repo name as the key.
replacing all dots with underscores.
> Replace dots with underscore in repo name

- src/config.js
- src/files.js
- src/reporter.js
Now you can configure `bundlesize` with path alone.
```
"bundlesize": [
{ "path": "./index.js" }
]
```
or 
```
bundlesize -f index.js
```
This means your build will always pass, but it will give the comparison with `master` as a message/warning.
> Make max size optional

- src/init-status.js
Currently if you run `bundlesize-init` you get:
```
Error: Cannot find module './src/build'
```
> Fix path of require statement

- README.md
It should probably be `kB` or `KB` (for 1000 or 1024 bytes respectively). `Kb` is mixed-case without really meaning anything
> Use correct capitalisation for "kB" in readme

- src/reporter.js
- src/shortener.js
I realised today that we could just shorten the url before sending it off to the github build status api.
The reason why storing it in firebase (as mentioned in #80) wont work as easily was because we might have to take backward compatibility into consideration and probably roll out a v2 for `/build` endpoint to tackle the older query-string and newer hash implementation.
The implementation below shortens the url (using the [google shortener api](https://developers.google.com/url-shortener/v1/getting_started#shorten)) which crosses 1024 chars. ~~You'll need to [get the API Key](https://developers.google.com/url-shortener/v1/getting_started#APIKey) and add it under the `@bundlesize_googleapikey` secret to your zeit/now settings.~~
Let me know what you think.
> Use goo.gl shortener for urls > 1024

- CONTRIBUTING.md
`environment.js` no longer exists. The information it used to hold now comes partly from `token.js` and partly from `ci-env`.
> Removing non existent environment.js file from CONTRIBUTING.md

- store/static/styles.css
> Update css to break filenames correctly

- README.md
There's a few similar projects to bundlesize, so it would be good to compare them in the readme. `travis-weigh-in` is one I've seen used in the past, and it's existed for a while longer than bundlesize has.
Recently I started building https://buildsize.org/ which takes a different approach: Rather than requiring a build-time dependency to be added, it's configured as a webhook via a GitHub App. This means that (at least at the moment) it only supports CI systems that support archiving of artifacts (such as CircleCI and AppVeyor), but on the other hand it means that no additional configuration is required, and no additional software is needed. You just add the webhook and it automatically tracks all artifacts. This is quite a departure from how bundlesize works so I figured I'd spin up a …
> Add "similar projects" section to the readme

- src/reporter.js
Comparing with master files does not seem to be working bec:
1. When checking if there are master files [here](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L50), the destructed variable `master` is being used for this check. That variable was set [before setting master on it](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L36). Fixed this by moving the destructing of `files` to after master was already set on it.
2. In the [setBuildStatus function](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L9), the name of the params of the function do not match the object that is being sent it. Fixed the names of it.
> Fix compare to master files

- store/views/build.pug
Since codeSponsor doesn't exist anymore (see also #192), this image 404s and the page doesn't exist anymore
> chore: remove sponsor from image

- README.md
- package-lock.json
- package.json
- pipe.js
- src/compressed-size.js
- src/config.js
- src/files.js
- src/reporter.js
Based on https://github.com/siddharthkp/bundlesize/pull/178.
Added a `-c`/`--compression` option that accepts `gzip`, `brotli` or `none`. Default is gzip.
This fixes #139 and closes #178 by implementing compression options.
The new functionality is also reflected in the reporter, that shows which compression is used. 
N/A
> feat: Add compression option (gzip|brotli|none)

- package-lock.json
- package.json
It's no longer used after the postinstall command was removed:
https://github.com/siddharthkp/bundlesize/commit/e0527bd56b7c88a1b424afee16ab99d275295bcf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
Removing the dependency avoids pulling in 39 packages unnecessarily.
Fixes #200.
(If it's preferred I can move it to `devDependencies` instead, however given that all of the opencollective references in this project point to their website and not the CLI, it presumably isn't regularly used.)
> Remove unused opencollective dependency

- package-lock.json
- package.json
This closes #294 and closes #298
Update brotli-size 0.0.1 to 0.0.3 for audit.
* brotli-size@0.0.1
* iltorb@1.3.10
* node-gyp@3.8.0
* tar@2.2.1
tar has a vulnerability.
update brotli-size 0.0.1 to 0.0.3 for audit.
* brotli-size@0.0.1
* iltorb@1.3.10
* node-gyp@3.8.0
* tar@2.2.1
tar has a vulnerability.
`npm install` failed why tar has a vulnerability.
- Version update
> chore: update brotli-size version

- README.md
Fix README.md. The example in the README.md is specifying the filename as `bundlesize.config.js` but it should be `bundlesize.config.json`.
Please review and merge. Thanks~!
> Fix README.md: filename extension should be json instead of js

- .travis.yml
- package.json
- packages/bundlesize-plugin-brotli/index.js
- packages/bundlesize-plugin-brotli/package.json
- packages/bundlesize-plugin-brotli/readme.md
- src/brotli.js
- src/compressed-size.js
From the looks of it, `iltorb`'s native bindings are large + don't play well on all platforms - and fails installs on windows and some CI environments.
1. For folks not using brotli compression at all, this is unnecessary overhead.
2. Native brotli compression support landed in node 10.16.0 (LTS), we don't need to include an external dependency for that
3. For folks using brotli and node < 10.16.0, this PR **is a breaking change** and will ask them to install `bundlesize-plugin-brotli` to continue
Changes introduced in this PR:
1. Remove `brotli-size` from dependencies
2. On Node >= 10.6.0, use `zlib.brotliCompressSync`
3. On Node < 10.6.0, ask to install `bundlesize-plugin-brotli`
4. Introduces `bundlesize-plugin-brotli`
Fixes #202, #283 and #213
Prior work: #220 #299
> Make brotli optional

- README.md
Added a note about requiring the `CI` env variable to be se.
Updated the readme to include more information on running bundlesize on different CI platforms
I wanted to test bundlesize locally so set the env vars locally to run the command.
The script failed as the env vars are not picked up unless `CI=true`
- I have read the **CONTRIBUTING** document. ✅ 
- I created an issue for the Pull Request fixes #329
> Add CI env to readme

- src/api.js
Fixes a broken link in one of the warning messages (currently commented though)
- Bugfix (non-breaking change which fixes an issue)
> Fixed broken link in github token missing warning
