- store/.env.sample
- store/index.js
- store/newrelic.js
- store/package-lock.json
- store/package.json
> add newrelic to store

- README.md
> Clarify gzip in README

- README.md
> add apollo to user list

- README.md
Add short section about 'How to contribute'
> Update readme(How to contribute)

- README.md
> docs: multiple + glob pattern

- src/files.js
Fail build if an invalid file path is given.
> Throw error if a wrong file path is given

- package.json
- src/api.js
- src/build.js
- src/config.js
- src/debug.js
- src/files.js
- src/reporter.js
This will help in finding those pesky bugs in people's CI
> Add debug mode

- README.md
- src/build.js
> Event agnostic build

- package-lock.json
- package.json
- src/reporter.js
Fixes #103 
- Adds Prettier as a simple pre-commit hook via lint-staged
- Ran Prettier on codebase to catch up
> Add prettier pre-commit hook

- README.md
> Update readme file for TODO list, fixes #109

- package-lock.json
- package.json
Solves https://github.com/siddharthkp/bundlesize/issues/89
Update from https://github.com/siddharthkp/prettycli/pull/5
> Upgrade prettycli to 1.4.3 (chalk 2.0.1)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Really need some opinion on the structure of this so any feedback would be awesome!
> Adds issues and PR templates

- src/init-status.js
Added missing [init-status](https://github.com/siddharthkp/bundlesize/blob/v0.14.2/src/init-status.js) file in [v0.14.3](https://github.com/siddharthkp/bundlesize/compare/v0.14.2...v0.14.3)
Closes issue #130
> Added init-status back, fixes #130

- README.md
Add npm stats to readme
closes [123](https://github.com/siddharthkp/bundlesize/issues/123) 
> Add npm stats to readme

- README.md
Updated Greenkeeper badge position in the readme as the new badge auto-added by Greenkeeper was showing in-between minimal setup header and the install code.
Top section badge section was not looking great, as it seemed the Greenkeeper badge was added in ad-hoc position.
- Readme update
> Updated Greenkeeper badge position

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/bundlesize ❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [more info]. See how it looks on this repo.
We have also added a postinstall script to let people know after npm|yarn install that you are welcoming donations (optional). [More info]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets
P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the …
> Activating Open Collective

- README.md
Omg!
Check out the build statuses on this PR: https://github.com/twbs/bootstrap/pull/24335
> Add bootstrap to "who uses bundlesize"

- README.md
> Added micromodal to the list of "who uses bundlesize?"

- README.md
- Breaking change (fix or feature that would cause existing functionality to change)
> add unistore to who uses bundlesize section

- README.md
As mentioned through the [CodeSponsor Twitter Handle](https://twitter.com/codesponsor/status/934114605969887232) and [post](https://us16.campaign-archive.com/?u=e95ff716114dbc939f8ef6100&id=b412420b3a), remove the (dead) CodeSponsor link from the README
As of December 8, 2017, [CodeSponsor shut down](https://us16.campaign-archive.com/?u=e95ff716114dbc939f8ef6100&id=b412420b3a). Cleaning up the README by removing the link. 
This fixes #191 
> Remove CodeSponsor Link from README

- README.md
- package-lock.json
- package.json
- pipe.js
- src/compressed-size.js
- src/config.js
- src/files.js
- src/reporter.js
Based on https://github.com/siddharthkp/bundlesize/pull/178 by @FezVrasta and https://github.com/siddharthkp/bundlesize/pull/194 by @SvanBoxel
Added a `-c`/`--compression` option that accepts `gzip`, `brotli` or `none`. Default is gzip.
This fixes #139 and closes #178 by implementing compression options.
The new functionality is also reflected in the reporter, that shows which compression is used. 
N/A
> Compression options

- src/reporter.js
Reimplementation of https://github.com/siddharthkp/bundlesize/pull/183
Provide a more detailed message in a GitHub PR as per #182 and #183 
To show a more relevant message in a GitHub PR when multiple files are checked.
See https://github.com/siddharthkp/bundlesize/pull/197#issuecomment-363546306
> Better multi-file messages

- README.md
The issue was created for tracking the progress on the integration with AppVeyor. Everyone who is interested can open the issue, click the "Subscribe" button and be notified via GitHub notifications :bell:
> chore(README): add link to AppVeyor issue

- src/token.js
See https://github.com/siddharthkp/bundlesize/issues/264
> honor BUNDLESIZE_GITHUB_TOKEN over GITHUB_TOKEN

- README.md
Update docs to include configuration for custom CI
See issue https://github.com/siddharthkp/bundlesize/issues/185
> Update docs to include configuration for custom CI

- package.json
- store/package.json
This patch upgrade `axios` dependency due to vulnerability described on [axios#1098](https://github.com/axios/axios/issues/1098)
It will provide use a safe version of `axios`
> security: upgrade axios due to vulnerability

- README.md
- Breaking change (fix or feature that would cause existing functionality to change)
> docs: ngxs uses bundlesize

- README.md
I only fixed two small typo errors
> (docs): fixed small error

- README.md
- Breaking change (fix or feature that would cause existing functionality to change)
> README: preact uses compressed-size-action

- .travis.yml
https://github.com/nodejs/Release
- Breaking change (fix or feature that would cause existing functionality to change)
> Travis CI: Node.js 8 is end of life

- package.json
Upgraded `axios` dependency as the current version has a security vulnerability. Upgraded `github-build` as well, as `github-build` depended on the vulnerable version of `axios`.
Fix for #380.
- Dependency upgrade (non-breaking change which fixes an issue)
> Upgrade axios, github-build dependencies
